function getNewsTemp(searchString) {

  const res = {
    status: 'ok',
    totalResults: 30,
    articles: [
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: "https://blue.d3.ru",
        category: "Небо",
        content: null,
        description: "https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/137566968_10222114295199366_4141631157116999659_o.jpg?_nc_cat=111&ccb=2&_nc_sid=8024bb&efg=eyJpIjoibCJ9&_nc_ohc=IqpecysDnBEAX8-z7Pt&_nc_ht=scontent-frx5-1.xx&tp=14&oh=389b0344c3f6a329932d8f7aff2ebe0…",
        publishedAt: "2021-01-10T15:52:14Z",
        source: { id: null, name: "Blue.d3.ru" },
        title: "Небо должно быть синим",
        url: "https://blue.d3.ru/nebo-dolzhno-byt-sinim-2099274/",
        urlToImage: "https://cdn.jpg.wtf/futurico/a7/dc/1610293434-a7dcffbdb356c7a2bfbac077ebb2182f.jpeg",
      },
      {
        author: "https://blue.d3.ru",
        category: "Небо",
        content: null,
        description: "https://scontent-frx5-1.xx.fbcdn.net/v/t1.0-9/fr/cp0/e15/q65/137566968_10222114295199366_4141631157116999659_o.jpg?_nc_cat=111&ccb=2&_nc_sid=8024bb&efg=eyJpIjoibCJ9&_nc_ohc=IqpecysDnBEAX8-z7Pt&_nc_ht=scontent-frx5-1.xx&tp=14&oh=389b0344c3f6a329932d8f7aff2ebe0…",
        publishedAt: "2021-01-10T15:52:14Z",
        source: { id: null, name: "Blue.d3.ru" },
        title: "Небо должно быть синим",
        url: "https://blue.d3.ru/nebo-dolzhno-byt-sinim-2099274/",
        urlToImage: "https://cdn.jpg.wtf/futurico/a7/dc/1610293434-a7dcffbdb356c7a2bfbac077ebb2182f.jpeg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
      {
        author: "https://politics.d3.ru",
        category: "Небо",
        content: null,
        description: "https://www.newsweek.com/richard-barnett-pictured-feet-pelosis-desk-capitol-riot-1559697↵ ↵↵ Видите дядьку на картинке? Зовут Ричард Барнетт. Говорит, что искал туалет в Конгрессе и зашел в офис спикера нижней палаты Нэнси Пелози. По дороге он поцарапался где…",
        publishedAt: "2021-01-07T21:51:45Z",
        source: { id: null, name: "Politics.d3.ru" },
        title: "Небо и земля",
        url: "https://politics.d3.ru/nebo-i-zemlia-2098315/",
        urlToImage: "https://cdn.jpg.wtf/futurico/fa/e2/1610055105-fae2476d8584d5bdbd647bb7882fe9d3.jpeg",
      },
      {
        author: null,
        category: "Небо",
        content: "6 90 , 16 .« , . . , , », .",
        description: "Грозы могут вызывать впечатляющие проявления молний, но одним из самых зрелищных и загадочных является красный спрайт – Самые лучшие и интересные посты по теме: Молния, небо, природное явление на развлекательном портале Fishki.net",
        publishedAt: "2021-01-08T11:28:14Z",
        source: { id: null, name: "Fishki.net" },
        title: "Спрайты: необычные молнии в небе над Луизианой",
        url: "https://fishki.net/3541927-sprajty-neobychnye-molnii-v-nebe-nad-luizianoj.html",
        urlToImage: "https://cdn.fishki.net/upload/post/2021/01/08/3541927/gallery/tn/001.jpg",
      },
    ]
  };

  return Promise.resolve(res);
}

function getNews(searchString) {

  const currentDate = new Date(); // сегодня
  const dtms = currentDate.valueOf();
  const days = 7;
  const fromDate = new Date(dtms - ((24 * 3600 * 1000) * days)); // от даты

  const url = `https://nomoreparties.co/news/v2/everything?` +
    `language=ru&` +
    `q=${searchString}&` +
    `from=${fromDate.toISOString()}&` +
    `to=${currentDate.toISOString()}&` +
    `pageSize=100&` +
    `apiKey=1da83ecf9e924ecfb22223be6534e5db`;
    // `apiKey=e16dc393d980454899c6c8150c9a1077`;
  const req = new Request(url);

  return fetch(req)
    .then(response => {
      if (response.ok) {
        return response.json();
      }
      return Promise.reject(`Ошибка: ${response.status}`);
    });
}

export {
  getNews,
  getNewsTemp
}
